// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"bytes"
	"encoding/json"
	"errors"
)

type StageType string

const (
	StageTypeStageSend      StageType = "StageSend"
	StageTypeStageDelay     StageType = "StageDelay"
	StageTypeStageWaitEvent StageType = "StageWaitEvent"
)

type Stage struct {
	StageSend      *StageSend
	StageDelay     *StageDelay
	StageWaitEvent *StageWaitEvent

	Type StageType
}

func CreateStageStageSend(stageSend StageSend) Stage {
	typ := StageTypeStageSend

	return Stage{
		StageSend: &stageSend,
		Type:      typ,
	}
}

func CreateStageStageDelay(stageDelay StageDelay) Stage {
	typ := StageTypeStageDelay

	return Stage{
		StageDelay: &stageDelay,
		Type:       typ,
	}
}

func CreateStageStageWaitEvent(stageWaitEvent StageWaitEvent) Stage {
	typ := StageTypeStageWaitEvent

	return Stage{
		StageWaitEvent: &stageWaitEvent,
		Type:           typ,
	}
}

func (u *Stage) UnmarshalJSON(data []byte) error {
	var d *json.Decoder

	stageSend := new(StageSend)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&stageSend); err == nil {
		u.StageSend = stageSend
		u.Type = StageTypeStageSend
		return nil
	}

	stageDelay := new(StageDelay)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&stageDelay); err == nil {
		u.StageDelay = stageDelay
		u.Type = StageTypeStageDelay
		return nil
	}

	stageWaitEvent := new(StageWaitEvent)
	d = json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&stageWaitEvent); err == nil {
		u.StageWaitEvent = stageWaitEvent
		u.Type = StageTypeStageWaitEvent
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u Stage) MarshalJSON() ([]byte, error) {
	if u.StageSend != nil {
		return json.Marshal(u.StageSend)
	}

	if u.StageDelay != nil {
		return json.Marshal(u.StageDelay)
	}

	if u.StageWaitEvent != nil {
		return json.Marshal(u.StageWaitEvent)
	}

	return nil, nil
}
