clients:
  - id: control
    secrets:
      - mysupersecret
    redirectUris:
      - http://80-formancehq-stack-b8pm8qm35s3.ws-eu71.gitpod.io:3000/auth/login
      - http://80-formancehq-stack-b8pm8qm35s3.ws-eu71.gitpod.io/auth/login
      - https://oauth.pstmn.io/v1/callback
    name: control
    postLogoutRedirectUris:
      - http://80-formancehq-stack-b8pm8qm35s3.ws-eu71.gitpod.io:3000/auth/destroy
      - http://80-formancehq-stack-b8pm8qm35s3.ws-eu71.gitpod.io/auth/destroy
